name: login_flutter
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment: 
  sdk: '>=2.17.5 <3.0.0'
dependencies: 
  flutter: 
    sdk: flutter
  cupertino_icons: ^1.0.2
  widgetbook: 2.0.5-beta
  flutter_svg: ^1.0.3
  auto_size_text: 3.0.0
dev_dependencies: 
  flutter_test: 
    sdk: flutter
  flutter_lints: ^2.0.0
flutter: 
  uses-material-design: true
  assets: 
    - packages/login_flutter/assets/images/ellipse2.svg
    - packages/login_flutter/assets/images/ellipse1.svg
    - packages/login_flutter/assets/images/ellipse1.png
    - packages/login_flutter/assets/images/ellipse2.png
    - packages/login_flutter/assets/images/rectangle1.svg
    - packages/login_flutter/assets/images/imagelogin1.png
    - packages/login_flutter/assets/images/rectangle3.svg
    - packages/login_flutter/assets/images/ellipse3.png
    - packages/login_flutter/assets/images/ellipse4.png
    - packages/login_flutter/assets/images/rectangle6.svg
    - packages/login_flutter/assets/images/ellipse5.png
    - packages/login_flutter/assets/images/vector.svg
    - packages/login_flutter/assets/images/bluetooth.png
    - packages/login_flutter/assets/images/alarm.png
    - packages/login_flutter/assets/images/reserve.svg
    - packages/login_flutter/assets/images/wifi.svg
    - packages/login_flutter/assets/images/signal.svg
    - packages/login_flutter/assets/images/sanstitre1pageswipevertical.png
